/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as SearchPacksRouteImport } from './routes/search.packs'
import { Route as SearchCardsRouteImport } from './routes/search.cards'
import { Route as PacksPackIdRouteImport } from './routes/packs.$packId'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchPacksRoute = SearchPacksRouteImport.update({
  id: '/search/packs',
  path: '/search/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchCardsRoute = SearchCardsRouteImport.update({
  id: '/search/cards',
  path: '/search/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackIdRoute = PacksPackIdRouteImport.update({
  id: '/packs/$packId',
  path: '/packs/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/search/cards': typeof SearchCardsRoute
  '/search/packs': typeof SearchPacksRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/search/': typeof SearchIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/search/cards': typeof SearchCardsRoute
  '/search/packs': typeof SearchPacksRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/search': typeof SearchIndexRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/search/cards': typeof SearchCardsRoute
  '/search/packs': typeof SearchPacksRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/search/': typeof SearchIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cards/$cardId'
    | '/packs/$packId'
    | '/search/cards'
    | '/search/packs'
    | '/series/$seriesId'
    | '/search/'
    | '/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cards/$cardId'
    | '/packs/$packId'
    | '/search/cards'
    | '/search/packs'
    | '/series/$seriesId'
    | '/search'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cards/$cardId'
    | '/packs/$packId'
    | '/search/cards'
    | '/search/packs'
    | '/series/$seriesId'
    | '/search/'
    | '/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  PacksPackIdRoute: typeof PacksPackIdRoute
  SearchCardsRoute: typeof SearchCardsRoute
  SearchPacksRoute: typeof SearchPacksRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/packs': {
      id: '/search/packs'
      path: '/search/packs'
      fullPath: '/search/packs'
      preLoaderRoute: typeof SearchPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/cards': {
      id: '/search/cards'
      path: '/search/cards'
      fullPath: '/search/cards'
      preLoaderRoute: typeof SearchCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packId': {
      id: '/packs/$packId'
      path: '/packs/$packId'
      fullPath: '/packs/$packId'
      preLoaderRoute: typeof PacksPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  PacksPackIdRoute: PacksPackIdRoute,
  SearchCardsRoute: SearchCardsRoute,
  SearchPacksRoute: SearchPacksRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  SearchIndexRoute: SearchIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
